version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    container_name: engagetrack-app

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
