apiVersion: apps/v1
kind: Deployment
metadata:
  name: engagetrack
  labels:
    app: engagetrack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engagetrack
  template:
    metadata:
      labels:
        app: engagetrack
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      containers:
      - name: engagetrack
        image: engagetrackacr.azurecr.io/engagetrack:latest
        ports:
        - containerPort: 8501
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
